name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  release-please:
    uses: ./.github/workflows/release-please-reusable.yml
    permissions:
      contents: write
      pull-requests: write
